export const enum ROUTES_ENUM {
  Dashboard = "dashboard",
  Info = "info",
  Rules = "rules",
  Decks = "decks",
  DeckListing = "deck-listing",
  Bookmarks = "bookmarks",
  BookmarkOverview = "bookmark-overview",
  BookmarkForm = "bookmark-form",
  CardOverview = "card-overview",
  CardForm = "card-form",
  Profile = "profile",
  Admin = "admin",
  Login = "login",
}
